services:
  - type: web
    name: lab5
    env: node
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    rootDir: backend
